[server]
port = 8501
address = "0.0.0.0"
baseUrlPath = "/projects/health-safety"
enableCORS = false
enableXsrfProtection = false

[browser]
serverAddress = "pxt.7a2.mytemp.website"
serverPort = 443

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730" 